GET http://localhost:8080/api/fahrten
Accept: application/json

###
GET http://localhost:8080/api/fahrten/1
Accept: application/json

> {% client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
});
  %}

###
GET http://localhost:8080/api/fahrten/1
Accept: application/json

###
POST http://localhost:8080/api/fahrten
Content-Type: application/json
Accept: application/json

{
  "nummer" : "FM89234",
  "vorname" : "Freddie",
  "nachname" : "Mercury"
}

> {% client.global.set("nummer", response.body.nummer) %}

###
GET http://localhost:8080/api/fahrten?nummer={{nummer}}
Accept: application/json

###
POST http://localhost:8080/api/fahrten
Content-Type: application/json
Accept: application/json

{
  "nummer" : "BM6732646",
  "vorname" : "Brian",
  "nachname" : "May"
}
###
POST http://localhost:8080/api/fahrten
Content-Type: application/json
Accept: application/json

{
  "nummer" : "JD2774223",
  "vorname" : "John",
  "nachname" : "Deacon"
}
###
POST http://localhost:8080/api/fahrten
Content-Type: application/json
Accept: application/json

{
  "nummer" : "RT723433",
  "vorname" : "Roger",
  "nachname" : "Taylor"
}
###
PUT http://localhost:8080/api/fahrten/5
Content-Type: application/json
Accept: application/json

{
  "nummer" : "RT723433",
  "vorname" : "ROGER",
  "nachname" : "Taylor"
}
###
PATCH http://localhost:8080/api/fahrten/5
Content-Type: application/json
Accept: application/json

{
  "nummer" : "RT723433",
  "nachname" : "TAYLOR"
}
###